//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Top4HoneyChainsMicroservices.AuthenticationApi.Models
{
    using System;
    
    public partial class Beekeeper
    {
        public Guid BeekeeperId { get; set; }
        public string ProfilePhoto { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string IdentityNumber { get; set; }
        public DateTime BirthDate { get; set; }
        public short ExperienceTime { get; set; }
        public int EducationLevel { get; set; }
        public string PhoneNumber { get; set; }
        public string AssociationMembership { get; set; }
        public string BusinessNumber { get; set; }
        public int BeekeepingPurposeType { get; set; }
        public int BeekeepingType { get; set; }
    }
}
