//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Top4HoneyChainsMicroservices.AuthenticationApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TOP4HoneyChainsDbEntities : DbContext
    {
        public TOP4HoneyChainsDbEntities()
            : base("name=TOP4HoneyChainsDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BeekeeperEducationLevel> BeekeeperEducationLevels { get; set; }
        public virtual DbSet<Beekeeper> Beekeepers { get; set; }
        public virtual DbSet<BeekeepingPurposeType> BeekeepingPurposeTypes { get; set; }
        public virtual DbSet<BeekeepingType> BeekeepingTypes { get; set; }
    }
}
